#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic except web and ssh ports


apt update -y
apt install ufw -y

sudo ufw default deny incoming

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable